# -*- coding: utf-8 -*-
"""Dijkstra_Practica_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHwUDjKDaoSpyjhfbl8dSsdkN0pUMRO-
"""

import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import random

c1 = random.randint(1,20)
c2 = random.randint(1,20)
c3 = random.randint(1,20)
c4 = random.randint(1,20)
c5 = random.randint(1,20)
c6 = random.randint(1,20)
c7 = random.randint(1,20)
c8 = random.randint(1,20)
c9 = random.randint(1,20)
c10 = random.randint(1,20)
c11 = random.randint(1,20)
c12 = random.randint(1,20)
c13 = random.randint(1,20)
c14 = random.randint(1,20)
c15 = random.randint(1,20)
c16 = random.randint(1,20)
c17 = random.randint(1,20)
c18 = random.randint(1,20)
c19 = random.randint(1,20)
c20 = random.randint(1,20)
c21 = random.randint(1,20)
c22 = random.randint(1,20)
c23 = random.randint(1,20)
c24 = random.randint(1,20)
c25 = random.randint(1,20)
c26 = random.randint(1,20)
c27 = random.randint(1,20)
c28 = random.randint(1,20)
c29 = random.randint(1,20)
c30 = random.randint(1,20)
c31 = random.randint(1,20)
c32 = random.randint(1,20)
c33 = random.randint(1,20)
c34 = random.randint(1,20)
c35 = random.randint(1,20)
c36 = random.randint(1,20)
c37 = random.randint(1,20)
c38 = random.randint(1,20)
c39 = random.randint(1,20)
c40 = random.randint(1,20)
c41 = random.randint(1,20)

nodos={'Santa Margarita','Santa Esther','Santa Anita','Pabellon','Villa','Lazaro Cardenas','Chapultepec','Jesus','Tabachines','San Isidro','Nogales','Aviacion','Revolucion','Americas','Centro','Calzada','Tesistan'}


aristas = [('Santa Margarita', 'Tesistan', c1), ('Tesistan', 'Santa Esther', c3), 
     ('Santa Esther', 'Villa', c9), ('Villa', 'Chapultepec', c10),
     ('Chapultepec', 'Jesus', c12), ('Jesus', 'Lazaro Cardenas', c11), 
     ('Lazaro Cardenas', 'Pabellon', c8), ('Pabellon', 'Santa Margarita', c2), 
     ('Santa Margarita', 'Tabachines', c4), ('Tabachines', 'San Isidro', c6), 
     ('San Isidro', 'Nogales', c5), ('Nogales', 'Tesistan', c7),
     ('Nogales','Aviacion',c12),('Aviacion','Santa Esther',c13),('Aviacion','Santa Esther',c14),
     ('Aviacion','Revolucion',c15),('Revolucion','Santa Esther',c16),('Revolucion','Villa',c17),
     ('Revolucion','Chapultepec',c18),('Aviacion','Jesus',c19)
     ,('Revolucion','Jesus',c20),('Revolucion','Americas',c21),('Jesus','Americas',c22),
     ('Aviacion','Santa Anita',c23),('Nogales','Tabachines',c24),('Tabachines','Centro',c25),
     ('Nogales','Centro',c26),('Calzada','Centro',c27),('Nogales','Calzada',c28),('Americas','Calzada',c29),
     ('Americas','Lazaro Cardenas',c30),('Calzada','Lazaro Cardenas',c31),('Santa Anita','Calzada',c32),
     ('Calzada','Pabellon',c33),('Centro','Pabellon',c34),('Centro','Santa Margarita',c35),('Santa Anita','Centro',c36),
     ('Nogales','Santa Anita',c37),('Nogales','Calzada',c38),('Santa Anita','Americas',c39),('Tesistan','Aviacion',c40),
     ('Santa Esther','Nogales',c41)]

G=nx.DiGraph()
G.add_nodes_from(nodos)
G.add_weighted_edges_from(aristas)

pos={'Santa Margarita':[4,18],'Santa Esther':[1,17],'Santa Anita':[8,10],'Pabellon':[-1,7],'Villa':[15,4],
   'Lazaro Cardenas':[15,1],'Chapultepec':[6,-4],'Jesus':[2,0],'Tabachines':[6,-1],'San Isidro':[9,-3],'Nogales':[1,4],'Aviacion':[1,9],'Revolucion':[7,19],'Americas':[19,5],'Centro':[12,11],'Calzada':[10,11],'Tesistan':[9,18]}


weight=nx.get_edge_attributes(G,'weight')
nx.draw_networkx_edge_labels(G, pos, edge_labels=weight)
nx.draw(G, pos=pos, with_labels=True)

best= nx.dijkstra_path(G, 'Jesus', 'Santa Margarita')
print("la mejor ruta es la siguiente:")
print(best)
best_road = nx.DiGraph()

for i in range(len(best)-1):
    best_road.add_edge(best[i], best[i+1])
    

#nx.draw(best_road, node_size = 1000, width = 1, with_labels = True, edge_color ="tab:red",)
nx.draw(best_road, pos=pos,with_labels = True, node_size = 500, width = 4, node_color = '#46E027',edge_color = '#182FD3')
plt.show()